stages:
  - build
  - test
  - increase-version
  - deploy-baget

variables:
  LIBRARY_DIRECTORY: "Wkg.AspNetCore/Wkg.AspNetCore"
  LIBRARY_PROJECT: "${LIBRARY_DIRECTORY}/Wkg.AspNetCore.csproj"
  LIBRARY_TEST_PROJECT: "Wkg.AspNetCore/Wkg.AspNetCoreTests/Wkg.AspNetCoreTests.csproj"
  TEST_ADAPTER_PROJECT: "Wkg.AspNetCore/Wkg.AspNetCore.TestAdapters/Wkg.AspNetCore.TestAdapters.csproj"
  MAJOR_VERSION: "8"
  MINOR_VERSION: "1"

include:
  - project: 'wkg/gitlab-templates'
    ref: 'v1.2.3'
    file:
      - '/jobs/build_dotnet_8.yml'
      - '/jobs/test_dotnet_8.yml'
      - '/jobs/increase_version.yml'
      - '/jobs/deploy_baget_dotnet_8.yml'

build-library:
  extends: .build
  variables:
    PROJECT_FILE_PATH: "${LIBRARY_PROJECT}"
    
build-test-adapters:
  extends: .build
  variables:
    PROJECT_FILE_PATH: "${TEST_ADAPTER_PROJECT}"

test-library:
  extends: .test
  variables:
    TEST_PROJECT_FILE_PATH: "${LIBRARY_TEST_PROJECT}"

increase-version:
  extends: .increase-version

deploy-library:
  extends: .deploy-baget
  variables:
    PROJECT_FILE_PATH: "${LIBRARY_PROJECT}"
    DOTNET_CI_VERSION_FILE: "${LIBRARY_DIRECTORY}/WkgAspNetCore.cs"
        
deploy-test-adapters:
  extends: .deploy-baget
  variables:
    PROJECT_FILE_PATH: "${TEST_ADAPTER_PROJECT}"